spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
        globally_quoted_identifiers: true

  jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/exception
    encoding: UTF-8


logging:
  level:
    root: warn
    org.springframework.web: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8081
